//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RampUpProjectBE.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int Log_Id { get; set; }
        public string Status { get; set; }
        public string Category { get; set; }
        public string Log_Function { get; set; }
        public string Message { get; set; }
        public System.DateTime Log_Datetime { get; set; }
        public Nullable<int> Object_Id { get; set; }
        public string Object_Type_ { get; set; }
    }
}
