//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RampUpProjectBE.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Payment_Id { get; set; }
        public int Payment_Status_Ref_Id { get; set; }
        public string Confirmation_Number { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<System.DateTime> Payment_Date { get; set; }
    
        public virtual Payment_Status_Ref Payment_Status_Ref { get; set; }
    }
}
