//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RampUpProjectBE.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phone
    {
        public int Phone_Id { get; set; }
        public Nullable<int> Branch_Id { get; set; }
        public Nullable<int> User_Id { get; set; }
        public string Phone_Number { get; set; }
        public string Phone_Type { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual User User { get; set; }
    }
}
