//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RampUpProjectBE.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RampUpProjectEntities : DbContext
    {
        public RampUpProjectEntities()
            : base("name=RampUpProjectEntities")
        {
        }

        public RampUpProjectEntities(string connectionString)
            : base(connectionString) {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<Business> Businesses { get; set; }
        public virtual DbSet<Card> Cards { get; set; }
        public virtual DbSet<Field> Fields { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Payment_Method_Ref> Payment_Method_Ref { get; set; }
        public virtual DbSet<Payment_Status_Ref> Payment_Status_Ref { get; set; }
        public virtual DbSet<PayPal> PayPals { get; set; }
        public virtual DbSet<Phone> Phones { get; set; }
        public virtual DbSet<Reservation> Reservations { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<User_Payment> User_Payment { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
    }
}
