//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RampUpProjectBE.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int Reservation_Id { get; set; }
        public int User_Id { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan Start_Time { get; set; }
        public System.TimeSpan End_Time { get; set; }
        public System.DateTime Creation_Date { get; set; }
        public int Field_Id { get; set; }
    
        public virtual User User { get; set; }
        public virtual Field Field { get; set; }
    }
}
